{% set name = "array-to-latex" %}
{% set version = "0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/josephcslater/array_to_latex/archive/{{ version }}.tar.gz
  sha256: b95645d126421fdd898d8c354e22db5e4eccf39aba53f268d05b9f7d905aff8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - numpy
    - clipboard

test:
  imports:
    - array_to_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/josephcslater/array_to_latex/
  summary: Converts a NumPy/SciPy array or Pandas Numerical DataFrame to a LaTeX
  license: MIT
  license_file: license.rst.txt

extra:
  recipe-maintainers:
    - thewchan
