{% set name = "array-to-latex" %}
{% set version = "0.83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/josephcslater/array_to_latex/archive/v{{ version }}.tar.gz
  sha256: 6cb2e7e377b7ae02ca258991aba2133aa127b4d17745610a674dc3407fe23878

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - numpy
    - pandas
    - clipboard

test:
  imports:
    - array_to_latex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/josephcslater/array_to_latex/
  summary: Converts a NumPy/SciPy array or Pandas Numerical DataFrame to a LaTeX
  license: MIT
  license_file: license.rst.txt

extra:
  recipe-maintainers:
    - thewchan
